<?php // Advanced Custom Fields

// Enqueue Metabox UI
function ashe_metabox_ui( $hook ) {
    global $post;

    // check if it is a post
    if ( ($hook == 'post-new.php' || $hook == 'post.php') && 'post' === $post->post_type ) {
        wp_enqueue_script( 'ashe-metabox-ui', get_theme_file_uri( '/inc/metaboxes/js/metabox-ui.js' ), array( 'jquery' ), false, true );
    }


}

add_action( 'admin_enqueue_scripts', 'ashe_metabox_ui' );


if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_592457fb53868',
	'title' => 'Category Options',
	'fields' => array (
		array (
			'key' => 'field_59245817d4d00',
			'label' => 'Show Header',
			'name' => 'show_category_header',
			'type' => 'radio',
			'instructions' => 'Whether to show <strong>Page Header</strong> on current category page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'yes',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59245934680a0',
			'label' => 'Show Logo',
			'name' => 'show_category_logo',
			'type' => 'radio',
			'instructions' => 'Whether to show <strong>Page Header Logo</strong> on current category page.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59245817d4d00',
						'operator' => '==',
						'value' => 'yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'yes',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_592459aa4cca2',
			'label' => 'Upload Custom Header Image',
			'name' => 'upload_custom_cat_header_image',
			'type' => 'image',
			'instructions' => 'This will replace <strong>Home Page Header</strong> image, which is globally set from the Theme Customizer > Header Image (section).',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59245817d4d00',
						'operator' => '==',
						'value' => 'yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59245ac34b725',
	'title' => 'Page Options',
	'fields' => array (
		array (
			'key' => 'field_59257c6ba9043',
			'label' => 'Show Page Title',
			'name' => 'show_page_title',
			'type' => 'radio',
			'instructions' => 'Whether to show <strong>Page Title</strong> on the current page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'yes',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59257c6ba9011',
			'label' => 'Show Page Drop Caps',
			'name' => 'show_page_dropcups',
			'type' => 'radio',
			'instructions' => 'Whether to show <strong>Drop Caps</strong> on the current page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59245e3707ce1',
			'label' => 'Show Featured Image',
			'name' => 'show_featured_image',
			'type' => 'radio',
			'instructions' => wp_kses_post( 'This will exclude featured image from the current page. <br>Note: This option does not work for <strong>WooCommerce</strong> pages.' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'yes',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59245ac368377',
			'label' => 'Show Header',
			'name' => 'show_page_header',
			'type' => 'radio',
			'instructions' => 'Whether to show <strong>Page Header</strong> on the current page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'yes',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59245ac36875e',
			'label' => 'Show Logo',
			'name' => 'show_page_logo',
			'type' => 'radio',
			'instructions' => 'Whether to show <strong>Page Header Logo</strong> on the current page.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59245ac368377',
						'operator' => '==',
						'value' => 'yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'yes',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59245ac368b46',
			'label' => 'Upload Custom Header Image',
			'name' => 'upload_custom_page_header_image',
			'type' => 'image',
			'instructions' => 'This will replace <strong>Home Page Header</strong> image, which is globally set from the Theme Customizer > Header Image (section).',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59245ac368377',
						'operator' => '==',
						'value' => 'yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_59245ec1d3832',
			'label' => 'Show Featured Slider',
			'name' => 'show_page_featured_slider',
			'type' => 'radio',
			'instructions' => wp_kses_post( 'Note: This option does not work for <strong>WooCommerce</strong> pages.' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_591350448c81c',
			'label' => 'Show This Page in Featured Slider',
			'name' => 'show_page_in_featured_slider',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_592546e68825b',
			'label' => 'Show Featured Links',
			'name' => 'show_page_featured_links',
			'type' => 'radio',
			'instructions' => wp_kses_post( 'Note: This option does not work for <strong>WooCommerce</strong> pages.' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59245b161999f',
			'label' => 'Show Sidebar',
			'name' => 'show_page_sidebar',
			'type' => 'radio',
			'instructions' => wp_kses_post( 'Note: <strong>WooCommerce Shop</strong> page Sidebars are controled <br> from the Theme Customizer > General Layouts (section).' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'none' => 'None',
				'lsidebar' => 'Left',
				'rsidebar' => 'Right',
				'lrsidebar' => 'Both',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'none',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59245dfd817ea',
			'label' => 'Full Width Content',
			'name' => 'full_width_page_content',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_592434b17acf0',
	'title' => 'Post Format: Audio',
	'fields' => array (
		array (
			'key' => 'field_592434be0c616',
			'label' => 'Audio Embed Code',
			'name' => 'audio_embed_code',
			'type' => 'textarea',
			'instructions' => 'Enter embed code of what you want to share, ex: Soundcloud.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59243761c4be2',
	'title' => 'Post Format: Gallery',
	'fields' => array (
		array (
			'key' => 'field_592437eb00209',
			'label' => 'Select Gallery Type',
			'name' => 'select_gallery_type',
			'type' => 'radio',
			'instructions' => 'Whether to display as Slideshow or Image Stack.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'slideshow' => 'Slideshow',
				'stacked' => 'Stacked',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Slideshow',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59243900dc9ed',
			'label' => 'Select Gallery Images',
			'name' => 'select_gallery_images',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59243c71acc08',
	'title' => 'Post Format: Link',
	'fields' => array (
		array (
			'key' => 'field_59243ca686d1a',
			'label' => 'Title',
			'name' => 'link_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59243cc9c434c',
			'label' => 'URL',
			'name' => 'link_url',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59243d055a3b3',
	'title' => 'Post Format: Quote',
	'fields' => array (
		array (
			'key' => 'field_59243d0cd5b93',
			'label' => 'Author',
			'name' => 'quote_author',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59243d3be6dad',
			'label' => 'Quote',
			'name' => 'quote_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59242e6be2da6',
	'title' => 'Post Format: Standard',
	'fields' => array (
		array (
			'key' => 'field_59242e7b69e25',
			'label' => 'Hide Featured Image',
			'name' => 'hide_featured_image',
			'type' => 'radio',
			'instructions' => 'This will exclude featured image from the single post page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_592430c291a56',
	'title' => 'Post Format: Video',
	'fields' => array (
		array (
			'key' => 'field_592430c934a85',
			'label' => 'Video Embed Code',
			'name' => 'video_embed_code',
			'type' => 'textarea',
			'instructions' => 'Enter embed code of what you want to share, ex: Youtube, Vimeo.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_592420379b851',
	'title' => 'Post Options',
	'fields' => array (
		array (
			'key' => 'field_59240767f2fab',
			'label' => 'Show Post Header',
			'name' => 'show_post_header',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'yes',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59240776f2fac',
			'label' => 'Show Header Logo',
			'name' => 'show_post_header_logo',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59240767f2fab',
						'operator' => '==',
						'value' => 'yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'yes',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_592456d4c6394',
			'label' => 'Upload Custom Header Image',
			'name' => 'upload_custom_post_header_image',
			'type' => 'image',
			'instructions' => 'This will replace <strong>Home Page Header</strong> image, which is globally set from the Theme Customizer > Header Image (section).',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59240767f2fab',
						'operator' => '==',
						'value' => 'yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5924061558641',
			'label' => 'Hide Sidebar',
			'name' => 'hide_post_sidebar',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5924064c1d866',
			'label' => 'Full Width Content',
			'name' => 'full_width_post_content',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_592950448c81c',
			'label' => 'Show in Featured Slider',
			'name' => 'show_in_featured_slider',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;